### ISSUE TITLE
Genkit AI Code Assist Badge

### ISSUE THREAD

**Issue by samyakkkk** [xavidop/awesome-firebase-genkit#10]
### Link to suggestion

https://app.commanddash.io/agent/github_firebase_genkit

### Describe your suggesiton

Hi! Genkit also has its own personalised AI assist. Would be cool to include it!

<a href="https://app.commanddash.io/agent/github_firebase_genkit"><img src="https://img.shields.io/badge/AI-Genkit%20Assist-EB9FDA"></a>

```
<a href="https://app.commanddash.io/agent/github_firebase_genkit"><img src="https://img.shields.io/badge/AI-Genkit%20Assist-EB9FDA"></a>
```

[Reference](https://medium.com/firebase-developers/build-firebase-genkit-nodejs-apps-with-dash-agents-skip-the-docs-258e067b3fdc?source=collection_home---4------3-----------------------)

**Comment by xavidop** [comment]
Sure @samyakkkk would you like to create a PR?

**Comment by xavidop** [comment]
Added!
